# -*- coding: utf-8 -*-
"""listandlistmethod.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iLjPtwsE46buA1IySVTiKyTwTZgbhOKW
"""

my_list = [0, 1, 232, 3, 4, 5, 6, 74, 33, 3, 100]
my_list1 = ["yellow", "apple", "orange", 3, 4, 5, 6, 74, 33, 3, 100]

# Modify my_list by appending 11 and removing 10
my_list.append(11)
my_list.remove(100)

# Print the modified my_list on a new line
print()  # This adds a new line
print(my_list)

#  sorting list using list sort method
my_list.sort();
print(my_list)


# for loop using list
for data in my_list:
  print(data)

my_list.clear()
my_list.append(55)
my_list.extend(my_list1)
# Print each element of my_list on the same line with a space between them
for item in my_list:
    print(item, end=" ")