# -*- coding: utf-8 -*-
"""Tuple and sets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qjFZWUR-Rc-W3yJf3tdMEbciOVd2YxTF
"""

# hello
print("**Welcome to file of tuples and sets and theirs Method**")

t = (1,2,4,5,6,7,8)

# tuple is immutable no one can change it no methods to add or remove data from it means t[0]="d"  we cant do that it thros error

print("index of 7 :",t.index(7))
print(t)

for item in t:
  print(item,end=" ")

print()

# sets in python and methods of sets same elements of sets will be removed automatically no repeating in sets

set0={1,2,3,4,5,1,2,1,1}
set1={1,2,3,4,5,8,9,7,1}
print(set0)
# print(set0.clear())
set0.clear()
set2={1,2,3,6,7,8};
print((set0.union(set1)).union(set2)) #it will return union of set0 and set1 and set2
print(set2.intersection(set1)) #it will return intersection of set0 and set1 common values

# Dictionary creation 
marks={"ab":{"number1":1,"number2":2}}
values=marks["ab"].values()
print(values)

#Two Ways to get values of subjects marks 

marks={"Umar":{"Maths":80,"CS":99,"English":88}}
values=marks["Umar"].values() #it will give me values Of My All Marks
print(values)
Maths=marks["Umar"]["Maths"] #it will give me value Of My Maths Marks
print(Maths)

values1=marks["Umar"]  #it will give me values Of My All Marks returns object i think so
print(values1)
print(values1["Maths"]) #it will give me value Of My Maths Marks